import { defineStore } from 'pinia'
import { computed, ref } from 'vue'
import { cancelCreateDrafts, commitCreateDrafts, getCreateDraft, preflightCreate, updateCreateDraft } from '../api/native-download/create'
import { uploadTorrent } from '../api/native-download/uploads'
import type { CreateDraftV2, CreateStep } from '../api/contracts/v2/create'

export const useCreateTaskStore = defineStore('create-task', () => {
  const open = ref(false); const step = ref<CreateStep>('input'); const rawInput = ref(''); const savePath = ref(''); const groupEnabled = ref(false); const groupLabel = ref(''); const uploadState = ref<'idle' | 'uploading' | 'done' | 'failed'>('idle'); const uploadProgress = ref(0); const draftsById = ref<Record<string, CreateDraftV2>>({}); const draftOrder = ref<string[]>([]); const preflightErrors = ref<Array<{ value: string; code: string; message: string }>>([]); const commitResults = ref<Array<{ draftId: string; ok: boolean; taskIds?: string[]; error?: { code: string; message: string } }>>([]); const error = ref<string | null>(null); let uploadAbort: AbortController | null = null;
  const drafts = computed(() => draftOrder.value.map((id) => draftsById.value[id]).filter(Boolean)); const readyDrafts = computed(() => drafts.value.filter((draft) => draft.state === 'ready' && (!['bt', 'magnet'].includes(draft.kind) || !draft.files.length || draft.selectedFileIndices.length > 0))); const committing = computed(() => step.value === 'committing');
  function reset() { open.value = false; step.value = 'input'; rawInput.value = ''; savePath.value = ''; groupEnabled.value = false; groupLabel.value = ''; uploadState.value = 'idle'; uploadProgress.value = 0; draftsById.value = {}; draftOrder.value = []; preflightErrors.value = []; commitResults.value = []; error.value = null; uploadAbort?.abort(); uploadAbort = null }
  function openForLinks(initial = '') { reset(); open.value = true; rawInput.value = initial; step.value = 'input' }
  function applyDraft(draft: CreateDraftV2) { draftsById.value = { ...draftsById.value, [draft.draftId]: draft }; if (!draftOrder.value.includes(draft.draftId)) draftOrder.value = [...draftOrder.value, draft.draftId] }
  async function preflightLinks() { error.value = null; preflightErrors.value = []; const values = rawInput.value.split(/\r?\n/).map((value) => value.trim()).filter(Boolean); const inputs = values.map((value) => ({ kind: 'link' as const, value })); if (!inputs.length) { error.value = '请先粘贴至少一个链接'; return } try { const response = await preflightCreate(inputs, savePath.value || undefined); response.results.forEach((result, index) => { if (result.ok && result.draft) { applyDraft(result.draft); if (!savePath.value) savePath.value = result.draft.savePath } else if (result.error) preflightErrors.value.push({ value: values[index], code: result.error.code, message: result.error.message }) }); step.value = response.results.some((result) => result.ok) ? 'options' : 'input'; } catch (cause) { error.value = cause instanceof Error ? cause.message : '预检失败' } }
  async function uploadTorrentFile(file: File) { uploadAbort?.abort(); uploadAbort = new AbortController(); uploadState.value = 'uploading'; uploadProgress.value = 0; error.value = null; try { const draft = await uploadTorrent(file, uploadAbort.signal, (progress) => { uploadProgress.value = progress }); applyDraft(draft); if (!savePath.value) savePath.value = draft.savePath; uploadState.value = 'done'; uploadProgress.value = 1; step.value = 'options' } catch (cause) { uploadState.value = 'failed'; if ((cause as Error).name !== 'AbortError') error.value = cause instanceof Error ? cause.message : 'torrent 上传失败' } }
  async function updateDraft(draft: CreateDraftV2, patch: { selectedFileIndices?: number[]; displayName?: string; savePath?: string; duplicateResolution?: string; options?: Record<string, unknown> }) { try { applyDraft(await updateCreateDraft({ draftId: draft.draftId, expectedRevision: draft.revision, ...patch })) } catch (cause) { error.value = cause instanceof Error ? cause.message : '草稿更新失败' } }
  async function changeSavePath(value: string) { savePath.value = value; const current = drafts.value.slice(); for (const draft of current) if (!['committed', 'cancelled', 'expired'].includes(draft.state)) await updateDraft(draft, { savePath: value }) }
  async function refreshMetadataDrafts() { for (const draft of drafts.value.filter((item) => item.state === 'metadata')) { try { applyDraft(await getCreateDraft(draft.draftId)) } catch {} } }
  async function commit() { if (!readyDrafts.value.length) return; step.value = 'committing'; error.value = null; try { const expected = Object.fromEntries(readyDrafts.value.map((draft) => [draft.draftId, draft.revision])); const label = groupLabel.value.trim(); const response = await commitCreateDrafts(readyDrafts.value.map((draft) => draft.draftId), expected, undefined, groupEnabled.value ? { label: label || '新建任务组' } : undefined); commitResults.value = response.results; step.value = 'result' } catch (cause) { error.value = cause instanceof Error ? cause.message : '创建任务失败'; step.value = 'options' } }
  async function cancelAndClose() { const ids = drafts.value.filter((draft) => !['committed', 'cancelled', 'expired'].includes(draft.state)).map((draft) => draft.draftId); if (ids.length) await cancelCreateDrafts(ids).catch(() => {}); reset() }
  return { open, step, rawInput, savePath, groupEnabled, groupLabel, uploadState, uploadProgress, drafts, readyDrafts, committing, commitResults, preflightErrors, error, reset, openForLinks, preflightLinks, uploadTorrentFile, refreshMetadataDrafts, updateDraft, changeSavePath, commit, cancelAndClose }
})
