<script setup lang="ts">
import type { DownloadPolicy } from '../../api/contracts/v2/policies'
const props = defineProps<{ modelValue: DownloadPolicy }>()
const emit = defineEmits<{ 'update:modelValue': [value: Partial<DownloadPolicy>]; 'proxy-secret': [value: { action: 'replace'; password: string }]; 'test-proxy': [] }>()
function patch(value: Partial<DownloadPolicy>) { emit('update:modelValue', value) }
</script>
<template>
  <section class="settings-card"><h2>网络</h2><label class="settings-check"><mdui-switch :checked="props.modelValue.p2pEnabled" @change="patch({ p2pEnabled: ($event.target as HTMLInputElement).checked })"></mdui-switch>P2P 加速</label><label class="settings-check"><mdui-switch :checked="props.modelValue.p2sEnabled" @change="patch({ p2sEnabled: ($event.target as HTMLInputElement).checked })"></mdui-switch>镜像 / P2S 加速</label><label>代理模式<mdui-select variant="outlined" :value="props.modelValue.proxy.mode" @change="patch({ proxy: { ...props.modelValue.proxy, mode: ($event.target as HTMLInputElement).value as 'direct' | 'http' | 'socks5' } })"><mdui-menu-item value="direct">直连</mdui-menu-item><mdui-menu-item value="http">HTTP</mdui-menu-item><mdui-menu-item value="socks5">SOCKS5</mdui-menu-item></mdui-select></label><template v-if="props.modelValue.proxy.mode !== 'direct'"><label>代理地址<mdui-text-field variant="outlined" :value="props.modelValue.proxy.host" @input="patch({ proxy: { ...props.modelValue.proxy, host: ($event.target as HTMLInputElement).value } })"></mdui-text-field></label><label>端口<mdui-text-field variant="outlined" type="number" :value="props.modelValue.proxy.port === null ? '' : String(props.modelValue.proxy.port)" @input="patch({ proxy: { ...props.modelValue.proxy, port: Number(($event.target as HTMLInputElement).value) } })"></mdui-text-field></label><label>用户名<mdui-text-field variant="outlined" :value="props.modelValue.proxy.username" @input="patch({ proxy: { ...props.modelValue.proxy, username: ($event.target as HTMLInputElement).value } })"></mdui-text-field></label><label>密码<mdui-text-field variant="outlined" type="password" autocomplete="new-password" placeholder="仅替换，不回显" @input="emit('proxy-secret', { action: 'replace', password: ($event.target as HTMLInputElement).value })"></mdui-text-field></label><mdui-button variant="tonal" class="secondary-button" @click="emit('test-proxy')">测试连接</mdui-button></template></section>
</template>
