<script setup lang="ts">
import type { DownloadPolicy } from '../../api/contracts/v2/policies'
const props = defineProps<{ modelValue: DownloadPolicy }>()
const emit = defineEmits<{ 'update:modelValue': [value: Partial<DownloadPolicy>]; 'proxy-secret': [value: { action: 'replace'; password: string }]; 'test-proxy': [] }>()
function patch(value: Partial<DownloadPolicy>) { emit('update:modelValue', value) }
</script>
<template>
  <section class="settings-card"><h2>网络</h2><label class="settings-check"><input type="checkbox" :checked="props.modelValue.p2pEnabled" @change="patch({ p2pEnabled: ($event.target as HTMLInputElement).checked })" />P2P 加速</label><label class="settings-check"><input type="checkbox" :checked="props.modelValue.p2sEnabled" @change="patch({ p2sEnabled: ($event.target as HTMLInputElement).checked })" />镜像 / P2S 加速</label><label>代理模式<select :value="props.modelValue.proxy.mode" @change="patch({ proxy: { ...props.modelValue.proxy, mode: ($event.target as HTMLSelectElement).value as 'direct' | 'http' | 'socks5' } })"><option value="direct">直连</option><option value="http">HTTP</option><option value="socks5">SOCKS5</option></select></label><template v-if="props.modelValue.proxy.mode !== 'direct'"><label>代理地址<input :value="props.modelValue.proxy.host" @input="patch({ proxy: { ...props.modelValue.proxy, host: ($event.target as HTMLInputElement).value } })" /></label><label>端口<input type="number" :value="props.modelValue.proxy.port ?? ''" @input="patch({ proxy: { ...props.modelValue.proxy, port: Number(($event.target as HTMLInputElement).value) } })" /></label><label>用户名<input :value="props.modelValue.proxy.username" @input="patch({ proxy: { ...props.modelValue.proxy, username: ($event.target as HTMLInputElement).value } })" /></label><label>密码<input type="password" autocomplete="new-password" placeholder="仅替换，不回显" @input="emit('proxy-secret', { action: 'replace', password: ($event.target as HTMLInputElement).value })" /></label><button class="secondary-button" @click="emit('test-proxy')">测试连接</button></template></section>
</template>
